// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriorityProducts.Models;

namespace PriorityProducts.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211003214920_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PriorityProducts.Models.Entities.Internal.SevenDays", b =>
                {
                    b.Property<string>("Product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime>("Last_Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Product_Price")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("Remaining_Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sales_Amount")
                        .HasColumnType("int");

                    b.HasKey("Product_Id");

                    b.ToTable("SevenDays");
                });

            modelBuilder.Entity("PriorityProducts.Models.Entities.Internal.ThirtyDays", b =>
                {
                    b.Property<string>("Product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime>("Last_Update")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Product_Price")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("Remaining_Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sales_Amount")
                        .HasColumnType("int");

                    b.HasKey("Product_Id");

                    b.ToTable("ThirtyDays");
                });
#pragma warning restore 612, 618
        }
    }
}
